spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/madpt;
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create #테이블 자동 생성
        properties:
            hibernate:
                #        show_sql : true
                format_sql : true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


