# 3.34.84.136
#db_MADPT_VERSION
spring:
    datasource:
        url: jdbc:mariadb://db_MADPT_VERSION:3306/MadPT
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update #테이블 자동 생성
        properties:
            hibernate:
                #        show_sql : true
                format_sql : true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


