name: Develop Branch Build Test

on:
  push:
    branches: 
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: DB Container Build Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DB_container/Dockerfile
          push: false

      - name: API Container Build Test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./API_container/Dockerfile
          push: false
